# -*- coding: utf-8 -*-
"""Thermal_sim_extract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECxVJ3vtlg3GffZJXqNPq2cDsJ5mw-3u
"""

import numpy as np


# >>>>>>>>>>>>>>>>>> computed par atom temp profile <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

ext_final_temp_profile = np.array([])

heat_profile_final = open('temp_profile.INDEX_thermalcond.0.0025')
for line in heat_profile_final:
  ext_temp_profile = ((line.split(' ')[-1]))
  ext_final_temp_profile = np.append(ext_final_temp_profile, ext_temp_profile)

ext_final_temp_profile = np.array(ext_final_temp_profile)
ext_final_temp_profile = ext_final_temp_profile[3:]
ext_final_temp_profile = ext_final_temp_profile.astype(float)
np.savetxt("ext_final_temp_profile_INDEX_thermalcond.txt", ext_final_temp_profile)



# >>>>>>>>>>>>>>>>>> lammps temp profile <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

ext_final_lammps_temp_profile = np.array([])

lammps_heat_profile_final = open('lammps_temp_profile.INDEX_thermalcond.0.0025')
for line in lammps_heat_profile_final:
  ext_lammps_temp_profile = ((line.split(' ')[-1]))
  ext_final_lammps_temp_profile = np.append(ext_final_lammps_temp_profile, ext_lammps_temp_profile)

ext_final_lammps_temp_profile = np.array(ext_final_lammps_temp_profile)
ext_final_lammps_temp_profile = ext_final_lammps_temp_profile[3:]
ext_final_lammps_temp_profile = ext_final_lammps_temp_profile.astype(float)
np.savetxt("ext_final_lammps_temp_profile_INDEX_thermalcond.txt", ext_final_lammps_temp_profile)


# >>>>>>>>>>>>>>>>>> mass density profile <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

ext_final_mass_density_profile = np.array([])

mass_density_profile_final = open('massdens_profile.INDEX_thermalcond.0.0025')
for line in mass_density_profile_final:
  ext_mass_density_profile = ((line.split(' ')[-1]))
  ext_final_mass_density_profile = np.append(ext_final_mass_density_profile, ext_mass_density_profile)

ext_final_mass_density_profile = np.array(ext_final_mass_density_profile)
ext_final_mass_density_profile = ext_final_mass_density_profile[3:]
ext_final_mass_density_profile = ext_final_mass_density_profile.astype(float)
np.savetxt("ext_final_mass_density_profile_INDEX_thermalcond.txt", ext_final_mass_density_profile)



# >>>>>>>>>>>>>>>>>> number density profile <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

ext_final_number_density_profile = np.array([])

number_density_profile_final = open('numdens_profile.INDEX_thermalcond.0.0025')
for line in number_density_profile_final:
  ext_number_density_profile = ((line.split(' ')[-1]))
  ext_final_number_density_profile = np.append(ext_final_number_density_profile, ext_number_density_profile)

ext_final_number_density_profile = np.array(ext_final_number_density_profile)
ext_final_number_density_profile = ext_final_number_density_profile[3:]
ext_final_number_density_profile = ext_final_number_density_profile.astype(float)
np.savetxt("ext_final_number_density_profile_INDEX_thermalcond.txt", ext_final_number_density_profile)